name: -= Code check =-
run-name: "Code check for ${{ github.event_name }}: ${{ github.ref_name}} by @${{ github.actor }}. Commit ID: ${{ github.sha }}"

on:
  push:
    branches:
      - 'main'
      - 'dev'
      - 'release'
    tags:
      - v*.*.* # or when a tagged release is created
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'release/*'

jobs:
  code-check:
    name: Code check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Run gradle check
        run: |
          echo "Running gradle check"
          ./gradlew check
      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/jacoco
    
